name: build-and-test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: "go.sum"
          go-version-file: "go.mod"
        id: go
      - name: Build
        run: |
          make build
      - name: Lint
        run: |
          make lint
      - name: Run tests
        run: |
          make test
