name: integration-test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set due_on"
        id: set-due-on
        run: echo "DUE_ON=$(date --iso-8601=seconds -d '13 days')" >> $GITHUB_ENV
      - name: "Create milestone"
        id: create_milestone
        uses: oinume/create-scheduled-milestone-action@main
        with:
          title: "v${{ github.run_id }}"
          state: "open"
          due_on: "${{ env.DUE_ON }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check outputs
        run: |
          test "${{ steps.create_milestone.outputs.number }}" != ""
